### model
model_name_or_path: /share/home/u21012/lqf/saved_model/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mllm_demo,identity,boundingBoxObjectNuscene_1,spacialDistanceNuscene_1, ladarMapLearning_train   # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 204800
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: /share/home/u21012/lqf/saved_model/RATP/Qwen2-vl-2b-spatial-ckpt-10.29
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
